general_cfg:
  algo_name: NoisyDQN
  env_name: gym
  device: cpu
  seed: 1
  mode: train
  collect_traj: false
  max_episode: 100
  max_step: 200
  mp_backend: ray
  n_workers: 2
  load_checkpoint: false
  load_path: Train_single_CartPole-v1_NoisyDQN_20230518-133737
  load_model_step: best
  online_eval: true 
  online_eval_episode: 10
  model_save_fre: 500
algo_cfg:
  value_layers:
    - layer_type: noisy_linear
      layer_size: [256]
      activation: relu
      std_init: 0.4
    - layer_type: noisy_linear
      layer_size: [256]
      activation: relu
      std_init: 0.4
  batch_size: 64
  buffer_type: REPLAY_QUE
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  lr: 0.0001
  target_update: 4
env_cfg:
  id: CartPole-v1
  render_mode: null