
general_cfg:
  joyrl_version: 0.5.2
  algo_name: TD3 
  env_name: gym 
  device: cuda   
  mode: train 
  collect_traj: false 
  n_interactors: 1
  load_checkpoint: false
  load_path: None
  load_model_step: best 
  max_episode: 1600 
  max_step: 1000
  seed: 2024 
  online_eval: true 
  online_eval_episode: 10
  model_save_fre: 1000

algo_cfg:
  critic_branch_layers:
    - name: state_branch
      layers:
      - layer_type: conv2d
        in_channel: 4
        out_channel: 16 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: pooling
        pooling_type: max2d
        kernel_size: 2
        stride: 2
        padding: 0
      - layer_type: conv2d
        in_channel: 16
        out_channel: 32 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: pooling
        pooling_type: avg2d
        kernel_size: 2
        stride: 2
        padding: 0
      - layer_type: flatten
      - layer_type: norm
        norm_type: LayerNorm
        normalized_shape: 512
      - layer_type: linear
        layer_size: [128]
        activation: relu
      - layer_type: linear
        layer_size: [32]
        activation: relu
    - name: action_branch
      layers:
      - layer_type: linear
        layer_size: [6]
        activation: relu
      - layer_type: linear
        layer_size: [6]
        activation: relu
  critic_merge_layers:
    - layer_type: linear
      layer_size: [6]
      activation: relu

  actor_merge_layers:
  actor_branch_layers:
    - name: state_branch
      layers:
      - layer_type: conv2d
        in_channel: 4
        out_channel: 16 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: pooling
        pooling_type: max2d
        kernel_size: 2
        stride: 2
        padding: 0
      - layer_type: conv2d
        in_channel: 16
        out_channel: 32 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: pooling
        pooling_type: avg2d
        kernel_size: 2
        stride: 2
        padding: 0
      - layer_type: flatten
      - layer_type: norm
        norm_type: LayerNorm
        normalized_shape: 512
      - layer_type: linear
        layer_size: [128]
        activation: relu
  actor_lr: 1.0e-4
  batch_size: 64 
  max_buffer_size: 1024100
  buffer_type: REPLAY_QUE
  critic_lr: 1.5e-3
  expl_noise: 0.45
  explore_steps: 200
  gamma: 0.99
  noise_clip: 0.5
  policy_freq: 2
  policy_noise: 0.2
  tau: 0.05
env_cfg:
  id: CarRacing-v2
  render_mode: null
  wrappers:
    - wrapper_name: CarV2SkipFrame
      skip: 5
      continue_flag: True
    - wrapper_name: GrayScaleObservation
    - wrapper_name: ResizeObservation
      shape: 84
    - wrapper_name: FrameStack
      num_stack: 4

