general_cfg:
  algo_name: VI
  device: cpu
  env_name: theAlley
  mode: test
  load_checkpoint: true
  load_path: Train_theAlley_VI_20221122-215228
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 100
algo_cfg:
  # value_layers:
  #   - layer_type: linear
  #     layer_dim: ['n_states',256]
  #     activation: relu
  #   - layer_type: linear
  #     layer_dim: [256,256]
  #     activation: relu
  #   - layer_type: linear
  #     layer_dim: [256,'n_actions']
  #     activation: none
  # batch_size: 64
  # max_buffer_size: 100000
  # epsilon_decay: 500
  # epsilon_end: 0.01
  # epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  # target_update: 4
