general_cfg:
  algo_name: TD3
  device: cpu
  env_name: gym
  eval_eps: 5
  eval_per_episode: 10
  load_checkpoint: true
  load_path: Train_gym_TD3_20230416-214019
  max_steps: 200
  mode: test
  n_workers: 1 # number of workers for parallel training
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.001
  batch_size: 100
  max_buffer_size: 1000000
  critic_hidden_dim: 256
  critic_lr: 0.001
  expl_noise: 0.1
  explore_steps: 1000
  gamma: 0.99
  noise_clip: 0.5
  policy_freq: 2
  policy_noise: 0.2
  tau: 0.005
  global_best_reward: -1800
env_cfg:
  id: Pendulum-v1
  new_step_api: true
