general_cfg:
  algo_name: TD3_BC
  device: cuda
  env_name: gym
  eval_eps: 5
  eval_per_episode: 1
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  mode: train
  new_step_api: true
  render: false
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 1
  wrapper: null
algo_cfg:
  actor_hidden_dim: 256
  actor_lr: 0.0003
  batch_size: 100
  max_buffer_size: 1000000
  critic_hidden_dim: 256
  critic_lr: 0.0003
  expl_noise: 0.1
  explore_steps: 1000
  gamma: 0.99
  noise_clip: 0.5
  policy_freq: 2
  policy_noise: 0.2
  tau: 0.005
  alpha: 5
  lmbda: 1
  normalize: false
  train_iterations: 1500 # 训练的迭代次数
  expert_path: tasks/Collect_gym_TD3_20230416-111040/traj/traj.pkl # 专家数据路径
env_cfg:
  id: Pendulum-v1
  new_step_api: true
