general_cfg:
  joyrl_version: 0.6.2.2
  algo_name: PPO
  env_name: gym 
  interactor_device: cpu
  learner_device: cuda 
  mode:  test # test
  exps_trucation_size: 1024
  exps_trucation_size_input_only: true
  is_learner_async: false
  load_checkpoint:  true
  # load_path: Train_ALE/Breakout-v5_PPO_20240814-141323 # 373.000 in 800 steps
  # load_path: Train_ALE/Breakout-v5_PPO_20240814-004435   # 252.000 in 800 steps
  load_path: Train_ALE/Breakout-v5_PPO_20240923-204459  # 408 in 512
  load_model_step: best 
  n_interactors:   1 # test
  max_episode:  3 # test
  max_step: 1200 
  seed: 202407
  online_eval: true 
  online_eval_episode: 1  # test
  model_save_fre: 1  # test
  policy_summary_fre: 1  # test
  interact_summary_fre: 1  # test
algo_cfg:
  mini_batch_normalize: true
  independ_actor: false
  return_form: gae # td 
  branch_layers:
    - name: feature_1
      layers:
      - layer_type: conv2d
        in_channel: 4
        out_channel: 32 
        kernel_size: 8
        stride: 4
        activation: relu
      - layer_type: conv2d
        in_channel: 32
        out_channel: 64 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: conv2d
        in_channel: 64
        out_channel: 64 
        kernel_size: 3
        stride: 1
        activation: relu
      - layer_type: flatten
      - layer_type: linear
        layer_size: [512]
        activation: relu
  buffer_type: ONPOLICY_QUE
  lr: 3.5e-4 # 2.5e-4
  actor_lr: 3.0e-4  
  critic_lr: 5.5e-4  
  entropy_coef: 0.001
  critic_loss_coef: 0.5
  eps_clip: 0.105
  gamma: 0.99
  gae_lambda: 0.95
  k_epochs: 3
  batch_size: 256
  sgd_batch_size: 128
  max_norm: 0.5
env_cfg:
  id: ALE/Breakout-v5
  render_mode:  null
  wrappers:
    - wrapper_name: BaseSkipFrame
      start_skip: 30
      skip: 4
      terminal_done_flag: true
      max_no_reward_count: 200
    - wrapper_name: GrayScaleObservation
    - wrapper_name: ResizeObservation
      shape: 84
    # - wrapper_name: ClipRewardEnv
    - wrapper_name: EpisodicLifeEnv
    - wrapper_name: FrameStack
      num_stack: 4
    - wrapper_name: MultiHeadObsWrapper
    - wrapper_name: MultiHeadActionWrapper
    - wrapper_name: FrameStack2Numpy

