general_cfg:
  algo_name: SAC
  continuous: true
  device: cpu
  env_name: LunarLanderContinuous-v2
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_LunarLanderContinuous-v2_SAC_20230402-170158
  max_steps: 500
  mode: test
  mp_backend: mp
  new_step_api: true
  render: true
  render_mode: human
  save_fig: true
  seed: 666
  show_fig: false
  test_eps: 20
  train_eps: 2000
  wrapper: null
algo_cfg:
  alpha: 0.2
  automatic_entropy_tuning: false
  batch_size: 64
  max_buffer_size: 1000000
  gamma: 0.99
  hidden_dim: 256
  lr: 0.001
  n_epochs: 1
  policy_type: Gaussian
  start_steps: 10000
  target_update_fre: 1
  tau: 0.005
